import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { db } from "@/db";
import { workerWeeklyScheduleDetails, workerWeeklySchedules } from "@/db/schema";
import { requireAdminSession } from "@/lib/auth";
import { getWeekEndDate } from "@/lib/dates";
import { jsonError } from "@/lib/http";
import { recalculateWeeklyAttendance } from "@/lib/weekly-tolerance";
type Detail={weekday:number;morningEnabled:boolean;morningEntryTime:string|null;morningExitTime:string|null;afternoonEnabled:boolean;afternoonEntryTime:string|null;afternoonExitTime:string|null};
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){if(!await requireAdminSession())return jsonError("No autorizado.",401);const id=Number((await params).id),url=new URL(request.url),week=url.searchParams.get("week");if(!Number.isInteger(id))return jsonError("Datos inválidos.",400);if(url.searchParams.get("list")==="1"){const schedules=await db.select({weekStart:workerWeeklySchedules.weekStart,weekEnd:workerWeeklySchedules.weekEnd}).from(workerWeeklySchedules).where(eq(workerWeeklySchedules.workerId,id)).orderBy(workerWeeklySchedules.weekStart);return NextResponse.json({schedules});}if(!week)return jsonError("La semana es requerida.",400);const [schedule]=await db.select().from(workerWeeklySchedules).where(and(eq(workerWeeklySchedules.workerId,id),eq(workerWeeklySchedules.weekStart,week))).limit(1);const details=schedule?await db.select().from(workerWeeklyScheduleDetails).where(eq(workerWeeklyScheduleDetails.weeklyScheduleId,schedule.id)):[];return NextResponse.json({schedule,details});}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){if(!await requireAdminSession())return jsonError("No autorizado.",401);const id=Number((await params).id);const body=await request.json().catch(()=>null) as {weekStart?:string;details?:Detail[]}|null;if(!Number.isInteger(id)||!body?.weekStart||!Array.isArray(body.details)||body.details.some(d=>d.weekday<1||d.weekday>7))return jsonError("Horario semanal inválido.",400);const weekEnd=getWeekEndDate(new Date(`${body.weekStart}T12:00:00-05:00`));let [schedule]=await db.select().from(workerWeeklySchedules).where(and(eq(workerWeeklySchedules.workerId,id),eq(workerWeeklySchedules.weekStart,body.weekStart))).limit(1);if(schedule){await db.update(workerWeeklySchedules).set({weekEnd,updatedAt:new Date()}).where(eq(workerWeeklySchedules.id,schedule.id));await db.delete(workerWeeklyScheduleDetails).where(eq(workerWeeklyScheduleDetails.weeklyScheduleId,schedule.id));}else {[schedule]=await db.insert(workerWeeklySchedules).values({workerId:id,weekStart:body.weekStart,weekEnd}).returning();}await db.insert(workerWeeklyScheduleDetails).values(body.details.map(d=>({...d,weeklyScheduleId:schedule.id,updatedAt:new Date()})));await recalculateWeeklyAttendance(id,new Date(`${body.weekStart}T12:00:00-05:00`),true);return NextResponse.json({ok:true,schedule});}
